<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitSummariesV2Seeder extends Seeder
{
    public function run(): void
    {
        $updated = 0;
        // Exact name matches
        $exact = [
            "Unit 1 \u2014 Phonics & Reading" => "## Phonics and Reading\n**Letter sounds:**\n- Short vowels: /a/ apple, /e/ egg, /i/ insect, /o/ orange, /u/ umbrella\n- Blending: c-a-t \u2192 cat, d-o-g \u2192 dog\n\n**Reading tips:**\n1. Sound out each letter\n2. Blend sounds together\n3. Read the whole word\n4. Check it makes sense",
            "Unit 1 - Greetings" => "## Greetings\n- Good morning! Good afternoon! Good evening!\n- How are you? \u2014 I am fine, thank you.\n- Polite words: Please, Thank you, Sorry, Excuse me\n- Always greet elders respectfully.",
            "Unit 2 - Colours" => "## Colours\n- Primary: Red, Yellow, Blue\n- Mix red+yellow=Orange, blue+yellow=Green, red+blue=Purple\n- Rainbow: Red, Orange, Yellow, Green, Blue, Indigo, Violet\n- Use colour adjectives: I have a **red** pencil.",
            "Unit 3 - My Family" => "## My Family\n- Father, Mother, Brother, Sister, Grandparents, Uncle, Aunt, Cousin\n- Possessive: my, your, his, her, our, their\n- My name is ___. I have ___ brothers and ___ sisters.",
            "Unit 4 - My Classroom" => "## My Classroom\n- Objects: desk, chair, blackboard, book, pen, pencil, ruler\n- Instructions: Open your book. Stand up. Listen carefully.\n- Prepositions: The book is **on** the desk. The bag is **under** the chair.",
            "Unit 5 - Parts of the Body" => "## Parts of the Body\n- Head: eyes, ears, nose, mouth\n- Body: neck, shoulders, chest, stomach\n- Arms: elbows, wrists, hands, fingers\n- Legs: knees, ankles, feet, toes\n- Hygiene: wash hands, brush teeth, bathe daily",
            "Unit 6 - Food I Like" => "## Food I Like\n- Carbohydrates: rice, bread, yam (energy)\n- Proteins: fish, meat, eggs, beans (muscles)\n- Vitamins: fruits and vegetables (health)\n- Cameroonian foods: Ndol\u00e9, Eru, Fufu corn, Plantain, Koki",
            "Unit 1 - My Neighbourhood" => "## My Neighbourhood\n- Places: school, market, hospital, police station, post office\n- People: teacher, doctor, police officer, farmer, trader\n- Directions: Turn left, turn right, go straight ahead\n- Prepositions: next to, opposite, behind, in front of",
            "Unit 2 - Farm Animals" => "## Farm Animals\n- Cow (milk), goat, sheep, pig, chicken (eggs), duck\n- Sounds: cow=moo, pig=oink, chicken=cluck, dog=bark\n- Products: cow\u2192milk/beef; chicken\u2192eggs/meat\n- Vocabulary: stable, pen, pasture, feed",
            "Unit 3 - Wild Animals" => "## Wild Animals\n- African animals: lion, elephant, giraffe, zebra, gorilla, chimpanzee\n- Habitats: forest (gorilla), savannah (lion/elephant), river (crocodile)\n- Endangered in Cameroon: gorillas, forest elephants\n- Conservation: protect national parks",
            "Unit 4 - Our Environment" => "## Our Environment\n- Natural: forests, rivers, mountains, oceans\n- Built: towns, roads, buildings, farms\n- Pollution: air (smoke), water (waste), land (plastic)\n- Protect: don't litter, plant trees, save water and electricity",
            "Unit 5 - How We Travel" => "## How We Travel\n- Land: car, bus, train, motorbike, bicycle\n- Water: boat, canoe, ship\n- Air: aeroplane, helicopter\n- Road safety: look left-right-left, use crossings, wear seatbelt",
            "Unit 1 - Places in Town" => "## Places in Town\n- Town hall, courthouse, hospital, pharmacy, bank, library\n- Asking directions: Excuse me, where is the hospital?\n- Go straight ahead, turn left, it is on your right\n- Modal verbs: can, could, would, should, must",
            "Unit 2 - Community Jobs" => "## Community Jobs\n- Doctor/Nurse: treats sick people\n- Teacher: educates children\n- Police officer: maintains law and order\n- Farmer: grows food\n- Engineer: builds roads and bridges\n- I want to be / I would like to become...",
            "Unit 3 - Weather and Seasons" => "## Weather and Seasons\n- Weather: sunny, cloudy, rainy, windy, stormy\n- Cameroon seasons: Dry (Nov-Mar) and Rainy (Apr-Oct)\n- Temperature: hot, warm, cool, cold\n- Describing: It is raining heavily today.",
            "Unit 1 - Our Country" => "## Our Country\n- Capital: Yaound\u00e9 (political), Douala (economic)\n- Languages: French and English\n- Currency: CFA Franc (FCFA)\n- Independence: 1st January 1960\n- Resources: petroleum, timber, cocoa, coffee, bananas",
            "Unit 1 - Plants and Animals" => "## Plants and Animals\n- Plant parts: roots, stem, leaves, flowers, fruits, seeds\n- Photosynthesis: CO\u2082 + Water + Sunlight \u2192 Glucose + Oxygen\n- Vertebrates: fish, amphibians, reptiles, birds, mammals\n- Food chains: grass \u2192 grasshopper \u2192 frog \u2192 snake \u2192 eagle",
            "Unit 1 - Staying Healthy" => "## Staying Healthy\n- Eat balanced diet, drink 6-8 glasses of water daily\n- Exercise 30+ minutes/day, sleep 8-10 hours/night\n- Malaria: use mosquito nets; Cholera: drink clean water\n- First aid: DRSABC \u2014 Danger, Response, Send help, Airway, Breathing, CPR",
            "Unit 1 - Our Culture" => "## Our Culture\n- 250+ ethnic groups, major: Beti, Bamileke, Fulani, Duala, Baka\n- Music: balafon, ngoma drum; Dances: bikutsi, makossa\n- Festivals: Ngondo, Nguon, FESTAC\n- Values: respect for elders, community solidarity, hospitality",
            "Unit 1 - Modern Technology" => "## Modern Technology\n- Devices: smartphones, tablets, laptops, smart TVs\n- Internet: search engines, social media, online learning, video calls\n- Benefits: communication, education, business, healthcare\n- Risks: cyberbullying, privacy, addiction, fake news\n- Digital citizenship: safe, kind, responsible online",
            "Unit 1 - Africa Overview" => "## Africa Overview\n- 54 countries, largest: Algeria, most populated: Nigeria\n- Longest river: Nile, highest mountain: Kilimanjaro (5,895m)\n- African Union (AU): founded 2002, HQ Addis Ababa, Ethiopia\n- Challenges: poverty, climate change, conflict",
            "Unit 2 - Being a Citizen" => "## Being a Citizen\n- Rights: education, health, vote, freedom of expression\n- Responsibilities: pay taxes, obey laws, respect others\n- Democratic participation: vote, stand for election, community decisions\n- Peace building: dialogue, mediation, tolerance, reconciliation",
            "Unit 3 - Protecting Nature" => "## Protecting Nature\n- Threats: deforestation, pollution, climate change, poaching\n- Solutions: plant trees, renewable energy, reduce-reuse-recycle\n- Congo Basin: 2nd largest rainforest in world (in southern Cameroon)\n- Endangered: mountain gorillas, forest elephants, chimpanzees",
            "Unit 1 - Decimals" => "## Decimals\n- 3.14: 3 ones, 1 tenth, 4 hundredths\n- Add/subtract: align decimal points\n- Fraction to decimal: divide numerator \u00f7 denominator\n- 3/4=0.75, 1/5=0.2, 7/10=0.7\n- Rounding: look at next digit \u2014 5 or more round up",
            "Unit 1 - Percentages" => "## Percentages\n- 50%=1/2, 25%=1/4, 75%=3/4, 10%=1/10\n- Calculate: 20% of 80 = (20/100)\u00d780 = 16\n- Profit% = (profit/cost price)\u00d7100\n- Discount: new price = original \u2212 (%\u00d7original)",
            "Unit 1 - Problem Solving" => "## Problem Solving\n1. Read the problem carefully\n2. Identify what is given and what is asked\n3. Choose the right operation (+, \u2212, \u00d7, \u00f7)\n4. Solve step by step\n5. Check your answer makes sense\n- D=S\u00d7T (distance, speed, time)\n- Always write units in your answer!",
            "Unit 5 - Statistics" => "## Statistics\n- Tally chart, frequency table: count and organise data\n- Bar graph: compare categories\n- Pie chart: show parts of a whole\n- Line graph: show change over time\n- Mean: sum\u00f7count; Median: middle value; Mode: most frequent; Range: highest\u2212lowest",
            "Unit 6 - Algebra Intro" => "## Introduction to Algebra\n- Variables: letters for unknown numbers (x+5=12 \u2192 x=7)\n- Expression: 3x+2 (no equals sign)\n- Equation: 3x+2=11 (has equals sign)\n- Solve: x+4=9 \u2192 x=5; 2x=14 \u2192 x=7\n- Substitution: if x=3, then 4x+2=4(3)+2=14",
            "Unit 1 Counting 0-10" => "## Counting 0 to 10\n0,1,2,3,4,5,6,7,8,9,10\n- Even: 0,2,4,6,8 / Odd: 1,3,5,7,9\n- More than: 7>5; Less than: 3<8; Equal: 4=4\n- Addition: 3+4=7; Subtraction: 7-3=4",
            "Unit 2 Counting 11-20" => "## Counting 11 to 20\n11,12,13,14,15,16,17,18,19,20\n- eleven, twelve, thirteen, fourteen, fifteen...\n- Place value: 15 = 1 ten + 5 units; 19 = 1 ten + 9 units",
            "Unit 2 Addition & Subtraction" => "## Addition and Subtraction\n- Addition (+): 8+5=13 \u2014 key words: plus, add, more, total\n- Subtraction (\u2212): 13\u22125=8 \u2014 key words: minus, difference, less, take away\n- Fact families: 3+4=7, 4+3=7, 7\u22123=4, 7\u22124=3",
            "Unit 6 Sets & Patterns" => "## Sets and Patterns\n- Set: group of objects with something in common\n- Venn diagrams: show what sets share\n- Patterns: repeating sequences (\u25cb\u25a1\u25b3\u25cb\u25a1\u25b3...)\n- Number patterns: 2,4,6,8 (add 2); 5,10,15,20 (add 5)",
            "Unit 1 Multiplication Tables" => "## Multiplication Tables\n- 2\u00d7: 2,4,6,8,10,12,14,16,18,20\n- 3\u00d7: 3,6,9,12,15,18,21,24,27,30\n- 5\u00d7: 5,10,15,20,25,30,35,40,45,50\n- 10\u00d7: 10,20,30,40,50,60,70,80,90,100\n- Tips: learn by heart, use patterns, practise daily",
            "Unit 1 Introduction to Division" => "## Division\n- Division (\u00f7): sharing equally\n- 12\u00f73=4 means 12 shared into 3 groups = 4 each\n- Division and multiplication are inverse: 3\u00d74=12, 12\u00f73=4\n- Key words: share, divide, group, each, remainder",
            "German Colonisation" => "## German Colonisation\n- 1884: Germany signs Treaty with Douala chiefs\n- 1914-1916: Allied forces defeat Germany in Cameroon\n- Rudolf Manga Bell: hanged 1914 for resisting land expropriation\n- Sultan Njoya: created Bamoun script\n- Chief Galega II: resisted German rule in Bali-Nyonga",
            "National Government" => "## National Government\n- Executive: President+Cabinet \u2014 implements laws\n- Legislative: National Assembly+Senate \u2014 makes laws\n- Judiciary: Supreme Court \u2014 applies justice\n- Presidential election every 7 years\n- 10 Regions, each with a Governor",
            "Regions" => "## Regions of Cameroon (10 Regions)\nCentre(Yaound\u00e9), Littoral(Douala), West(Bafoussam), NW(Bamenda), SW(Buea), South(Ebolowa), East(Bertoua), North(Garoua), Adamawa(Ngaound\u00e9r\u00e9), Far North(Maroua)\n- Anglophone: North West and South West regions",
            "Pre-colonial Cameroon" => "## Pre-colonial Cameroon\n- Bamoun Kingdom: Sultan Njoya created Shumom script, Foumban Palace\n- Bali-Nyonga: Chamba warriors, Chief Galega\n- Fulani Emirates: Adamawa, Ngaound\u00e9r\u00e9\n- Douala chiefdoms: coastal trading centres\n- Baka people: oldest inhabitants of Cameroon's forests",
            "International Organisations" => "## International Organisations\n- UN: 193 members, founded 1945, HQ New York\n- UNICEF(children), WHO(health), UNESCO(education/culture), FAO(food)\n- African Union: 55 members, HQ Addis Ababa, promotes African unity\n- CEMAC: Economic community of Central African states",
            "Economic Activities" => "## Economic Activities\n- Primary: agriculture (cocoa, coffee, palm oil), fishing, forestry, mining, petroleum\n- Secondary: food processing, timber, aluminium, construction\n- Tertiary: trade, transport, banking, tourism, education\n- Exports: oil, timber, cocoa, coffee, aluminium\n- Partners: France, China, USA, Nigeria",
            "Africa Before Colonisation" => "## Africa Before Colonisation\n- Ancient Egypt: pyramids, hieroglyphics, pharaohs\n- Mali Empire: Mansa Musa, Timbuktu (learning centre)\n- Songhai Empire: largest West African empire\n- Trans-Saharan trade: gold and salt; spread of Islam\n- Berlin Conference 1884: divided Africa between European powers",
            "Environmental Issues" => "## Environmental Issues\n- Climate change, deforestation (10M hectares/year lost globally)\n- Lake Chad: 80% smaller since 1960s\n- Deforestation of Congo Basin\n- SDGs: 17 goals (2015), Goal 13: Climate Action, Goal 15: Life on Land\n- Reduce, Reuse, Recycle \u2014 start at home!",
            "Road to Independence" => "## Road to Independence\n- 1884: Germany colonises Cameroon\n- 1916: France and Britain divide Cameroon\n- 1960: French Cameroun independence (1st January)\n- 1961: Southern Cameroons joins \u2192 Federal Republic\n- 1972: United Republic of Cameroon\n- 1984: Republic of Cameroon\n- First President: Ahmadou Ahidjo",
            "Continents and Oceans" => "## Continents and Oceans\n- 7 Continents: Africa(54 countries), Asia(largest area), Europe, N.America, S.America, Oceania, Antarctica\n- 5 Oceans: Pacific(largest) \u2192 Atlantic \u2192 Indian \u2192 Southern \u2192 Arctic\n- Equator: 0\u00b0 latitude divides North and South hemispheres",
        ];
        foreach ($exact as $name => $summary) {
            $updated += DB::table('units')->where('name',$name)->whereNull('summary')->update(['summary'=>$summary,'updated_at'=>now()]);
        }
        // Pattern matches
        $patterns = [
            "%Grammar%" => "## Grammar\n- Nouns: names (common & proper)\n- Pronouns: I, you, he, she, it, we, they\n- Verbs: action words \u2014 present, past, future tenses\n- Adjectives: describing words (big, small, red)\n- Adverbs: describe verbs (quickly, slowly)\n- Conjunctions: and, but, or, because\n- A sentence must have a subject and a verb.",
            "%Vocabulary%" => "## Vocabulary\n- Synonyms (similar): happy=joyful, big=large\n- Antonyms (opposite): hot\u2260cold, brave\u2260cowardly\n- Word families: teach\u2192teacher\u2192teaching\n- Prefixes: un-(not), re-(again), pre-(before)\n- Suffixes: -ful, -less, -er, -ing\n- Use new words in sentences daily",
            "%Comprehension%" => "## Reading Comprehension\n1. Read the title and predict content\n2. Read the passage carefully at least twice\n3. Identify the main idea\n4. Find supporting details\n5. Answer using evidence from the text\n- Literal: answer in text; Inferential: use clues; Vocabulary: meaning in context",
            "%Writing%" => "## Writing Skills\n- Narrative: tells a story (beginning, middle, end)\n- Descriptive: describes vividly using senses\n- Persuasive: gives reasons to convince\n- Paragraph: topic sentence + supporting sentences + concluding sentence\n- Always plan before you write!",
            "%Literature%" => "## Literature\n- Characters, Setting, Plot, Theme, Conflict\n- Prose: novels, short stories\n- Poetry: poems, songs, rhyme and rhythm\n- Drama: plays, scripts\n- Figurative language: simile, metaphor, personification, idiom",
            "%Numbers%" => "## Numbers and Operations\n- Addition (+), Subtraction (\u2212), Multiplication (\u00d7), Division (\u00f7)\n- BODMAS: Brackets\u2192Orders\u2192Division\u2192Multiplication\u2192Addition\u2192Subtraction\n- Even: end in 0,2,4,6,8; Odd: end in 1,3,5,7,9\n- Prime: exactly 2 factors",
            "%Fractions%" => "## Fractions and Decimals\n- Fraction: numerator/denominator (1/2, 3/4)\n- Equivalent: 1/2=2/4=4/8\n- HCF: largest shared factor; LCM: smallest shared multiple\n- Decimal: 0.5=1/2, 0.25=1/4, 0.75=3/4\n- Add/subtract fractions: same denominator needed",
            "%Geometry%" => "## Geometry\n- Triangle: 3 sides, angles=180\u00b0; Rectangle: 4 right angles; Circle: radius, diameter\n- Right angle=90\u00b0; Acute<90\u00b0; Obtuse>90\u00b0; Straight=180\u00b0\n- Area: rectangle=l\u00d7w; triangle=\u00bd\u00d7b\u00d7h\n- 3D shapes: cube, cuboid, sphere, cylinder, cone",
            "%Measurement%" => "## Measurement\n- Length: mm\u2192cm(\u00d710)\u2192m(\u00d7100)\u2192km(\u00d71000)\n- Mass: g\u2192kg(\u00d71000)\n- Capacity: ml\u2192l(\u00d71000)\n- Time: 60sec=1min, 60min=1hr, 24hr=1day, 7days=1week, 12months=1year\n- Speed = Distance \u00f7 Time",
            "%Money%" => "## Money and Statistics\n- Change = Amount paid \u2212 Cost price\n- Profit = Selling price \u2212 Cost price\n- Percentage profit = (profit/cost price)\u00d7100\n- Graphs: bar (compare), pie (parts of whole), line (change over time)\n- Mean=sum\u00f7count; Median=middle; Mode=most frequent",
            "%Science%" => "## Science and Technology\n- Skeletal system: 206 bones\n- Photosynthesis: CO\u2082+Water+Sunlight\u2192Glucose+Oxygen\n- States of matter: solid, liquid, gas\n- Food chains: producer\u2192primary consumer\u2192secondary consumer\n- Energy types: kinetic, potential, thermal, light, electrical",
            "%ICT%" => "## ICT\n- Input: keyboard, mouse; Output: monitor, printer\n- CPU: brain of computer; RAM: temporary memory; HDD: storage\n- OS: Windows, Ubuntu, Android\n- Shortcuts: Ctrl+C(copy), Ctrl+V(paste), Ctrl+Z(undo)\n- Internet safety: strong passwords, HTTPS, no personal info to strangers",
            "%Citizenship%" => "## Citizenship\n- Flag: green(forests), red(unity), yellow(sun) + gold star\n- National Day: 20th May; Anthem: O Cameroon, Cradle of Our Forefathers\n- Government: Executive(President), Legislative(Assembly), Judiciary(Courts)\n- Children's rights: education, health, protection, name/nationality\n- Civic duties: obey law, pay taxes, vote, protect environment",
            "%History%" => "## History\n- Sources: written, oral, archaeological\n- Ancient civilisations: Egypt, Greece, Rome\n- Slave trade: 15th-19th century\n- Germany in Cameroon: 1884-1916\n- Resistance heroes: Rudolf Manga Bell, Sultan Njoya, Chief Galega II\n- Cameroon independence: 1st January 1960; Reunification: 1st October 1961",
            "%Geography%" => "## Geography\n- Cameroon: Mount Cameroon (4095m), Sanaga River, 4 climate zones\n- Economic activities: cocoa, coffee, petroleum, timber, fishing\n- 7 continents: Africa, Asia, Europe, Americas, Oceania, Antarctica\n- 5 oceans: Pacific (largest), Atlantic, Indian, Southern, Arctic\n- Climate change: caused by burning fossil fuels",
            "%Social Studies%" => "## Social Studies\n- Community: family, neighbourhood, local, national, global\n- History: sources, civilisations, independence, development\n- Geography: physical features, climate, economic activities\n- Citizenship: rights, duties, government, elections\n- Environmental stewardship: use resources responsibly",
            "%Home Economics%" => "## Home Economics\n- Balanced diet: carbs, proteins, fats, vitamins, minerals, water\n- Food hygiene: wash hands, store properly, check expiry dates\n- Needlework: running stitch, back stitch, hem stitch\n- Housekeeping: clean, organised, safe home\n- Life skills: budgeting, cooking, communication, teamwork",
            "%Arts%" => "## Arts and Crafts\n- Drawing: start with basic shapes, add details, colour\n- Colours: primary(red,yellow,blue) \u2192 secondary(orange,green,purple)\n- Moulding: shape clay or papier-m\u00e2ch\u00e9 into 3D forms\n- Weaving: interlace strips to make mats and baskets\n- Cameroonian crafts: beadwork, woodcarving, pottery, kente",
            "%Physical Education%" => "## Physical Education\n- Benefits: strong body, better concentration, good mood\n- Athletics: sprints, long jump, high jump, throws (shot put, discus, javelin)\n- Team sports: football(11), basketball(5), volleyball(6), cricket(11)\n- Training principles: Frequency, Intensity, Time, Type (FITT)\n- Always warm up before exercising!",
            "%National Languages%" => "## National Languages and Cultures\n- ~275 local languages in Cameroon\n- Major groups: Bantu, Semi-Bantu, Chadic, Fulfulde\n- Oral traditions: folktales, proverbs, songs, riddles\n- Cultural ceremonies: birth, coming of age, marriage, funerals\n- Preserve: use your language, attend ceremonies, tell ancestral stories",
            "%Artistic%" => "## Artistic Activities\n- Drawing and colouring, cutting and pasting\n- Singing songs and rhymes, dancing and movement\n- Moulding with clay or playdough\n- Colours: Red, Blue, Yellow, Green, Orange, Purple, Black, White\n- Shapes: Circle, Square, Triangle, Rectangle",
            "%FSLC%" => "## FSLC Preparation\n- Subjects: English, French, Mathematics, Science, Citizenship\n- Read each question twice before answering\n- Show all working in Mathematics\n- Manage your time \u2014 don't spend too long on one question\n- Write clearly and check your answers before submitting",
            "%Phonics%" => "## Phonics\n- Short vowels: /a/ apple, /e/ egg, /i/ insect, /o/ orange, /u/ umbrella\n- Digraphs: sh, ch, th, wh, ph\n- Blends: bl, br, cl, cr, dr, fl, fr, gl, gr, pl, pr, st, tr\n- Blending: sound out \u2192 blend \u2192 read: /k//\u00e6//t/ \u2192 cat\n- Practise 15 minutes of phonics reading daily",
        ];
        foreach ($patterns as $pat => $summary) {
            $updated += DB::table('units')->where('name','like',$pat)->whereNull('summary')->update(['summary'=>$summary,'updated_at'=>now()]);
        }
        echo 'V2: ' . $updated . ' units updated.' . PHP_EOL;
    }
}