import { useEffect, useState } from 'react'
type Child={id:number;name:string;level:string}; type Entry={id:number;weekday:number;start_time:string;end_time:string;subject_name:string;notes?:string|null}
const DAYS=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']
async function token(){await fetch('/sanctum/csrf-cookie',{credentials:'same-origin'});return decodeURIComponent(document.cookie.split('; ').find(v=>v.startsWith('XSRF-TOKEN='))?.split('=').slice(1).join('=')||'')}
export default function SchoolTimetable({children}:{children:Child[]}){
 const [childId,setChildId]=useState(children[0]?.id||0),[entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const [form,setForm]=useState({weekday:1,start_time:'08:00',end_time:'09:00',subject_name:'',notes:''})
 const load=async(id=childId)=>{if(!id)return setEntries([]);const r=await fetch(`/api/children/${id}/timetable`,{credentials:'same-origin',headers:{Accept:'application/json'}});if(r.ok)setEntries(await r.json())}
 useEffect(()=>{load(childId)},[childId])
 const add=async()=>{setError('');setSaving(true);try{const r=await fetch(`/api/children/${childId}/timetable`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-XSRF-TOKEN':await token(),Accept:'application/json'},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||'Impossible d’ajouter ce cours.');setForm(f=>({...f,subject_name:'',notes:''}));await load()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 const remove=async(id:number)=>{if(!confirm('Retirer ce cours ?'))return;const r=await fetch(`/api/children/${childId}/timetable/${id}`,{method:'DELETE',credentials:'same-origin',headers:{'X-XSRF-TOKEN':await token(),Accept:'application/json'}});if(r.ok)await load()}
 if(!children.length)return <div>Ajoute d’abord un enfant.</div>
 return <div><div style={{background:'var(--card)',border:'1.5px solid var(--border)',borderRadius:18,padding:16,marginBottom:16}}>
  <div style={{fontSize:18,fontWeight:900}}>📚 Emploi du temps scolaire</div><div style={{fontSize:12,color:'var(--text-soft)',margin:'5px 0 14px'}}>La passerelle entre l’école et les révisions EduMaison.</div>
  <select value={childId} onChange={e=>setChildId(Number(e.target.value))} style={{width:'100%',padding:10,marginBottom:10}}>{children.map(c=><option key={c.id} value={c.id}>{c.name} · {c.level}</option>)}</select>
  <div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr 2fr',gap:8}}><select value={form.weekday} onChange={e=>setForm(f=>({...f,weekday:Number(e.target.value)}))}>{DAYS.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select><input type="time" value={form.start_time} onChange={e=>setForm(f=>({...f,start_time:e.target.value}))}/><input type="time" value={form.end_time} onChange={e=>setForm(f=>({...f,end_time:e.target.value}))}/><input placeholder="Matière" value={form.subject_name} onChange={e=>setForm(f=>({...f,subject_name:e.target.value}))}/></div>
  <input style={{width:'100%',boxSizing:'border-box',marginTop:8}} placeholder="Note facultative" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/>{error&&<div style={{color:'#B91C1C',fontSize:12}}>{error}</div>}<button onClick={add} disabled={saving||!form.subject_name.trim()} style={{marginTop:10,padding:'9px 16px',background:'#1D6B2A',color:'white',border:0,borderRadius:10,fontWeight:900}}>{saving?'Ajout…':'+ Ajouter le cours'}</button>
 </div>{DAYS.map((d,i)=>{const rows=entries.filter(e=>e.weekday===i+1);return rows.length?<div key={d} style={{background:'var(--card)',borderRadius:14,padding:14,marginBottom:10}}><b style={{color:'#1D6B2A'}}>{d}</b>{rows.map(e=><div key={e.id} style={{display:'flex',gap:10,padding:'8px 0',borderTop:'1px solid var(--border)'}}><b>{e.start_time.slice(0,5)}–{e.end_time.slice(0,5)}</b><span style={{flex:1}}>{e.subject_name}{e.notes?` · ${e.notes}`:''}</span><button onClick={()=>remove(e.id)} style={{border:0,background:'transparent',color:'#B91C1C'}}>Supprimer</button></div>)}</div>:null})}{!entries.length&&<div style={{textAlign:'center',padding:30}}>Aucun cours saisi.</div>}</div>
}
